### ISSUE TITLE
Update to django rest framework 3.0

### ISSUE THREAD

**Issue by rolandgeider** [rolandgeider/wger#106]
Update to django rest framework 3.0

**Comment by rlaszlo** [comment]
Hi @rolandgeider ,

I have experience with Django Rest Framework, mostly with 2.X, but I think I can help with the update.

Do you have anything in mind for the update process?

**Comment by rolandgeider** [comment]
hi @rlaszlo ,

basically, everything should still work afterwards ;) I have not looked at this much besides reading the changelogs for the newer DRF releases, so I can't say how much work this is actually going to be and what got deprecated.

**Comment by rlaszlo** [comment]
Ok, then I will try to update to the latest, run the tests and hope for the best. :)

**Comment by rolandgeider** [comment]
I know I pinned down the DRF version because there were some bugs. Supposedly they got fixed in 3.x... :)

**Comment by rolandgeider** [comment]
Done with #162
