### ISSUE TITLE
captcha missing

### ISSUE THREAD

**Issue by fitbodylife** [rolandgeider/wger#116]
i'm missing the captcha on the register page.  can you tell me how to get it?  is there a way this software is able to manage multiple people from one account

**Comment by rolandgeider** [comment]
Hi! Do you mean in a local installation? You either need to enter reCaptcha keys in your settings.py file or patch the registration view (core/views/user.py registration() >> ```FormClass = RegistrationFormNoCaptcha ```). But you are right that it is not clear how to do it, I'll probably make this configurable and deactivated by default.

And as for being able to manage multiple people, the software is constructed so that every workout, log, etc, belongs to the user that created it. The closest there is for this is the gym management, where a trainer has an overview over other users.

**Comment by fitbodylife** [comment]
Great.  how do i activate or use the gym management

Khoi Nguyen
Managing Director
3400 W MacArthur Blvd. Suite C
Santa Ana, CA 92704
714-902-9584 ext 700
714-362-9068 fax
www.mobilechipmunk.com

        


On January 4, 2015 at 1:24:29 AM, Roland Geider (notifications@github.com) wrote:

Hi! Do you mean in a local installation? You either need to enter reCaptcha keys in your settings.py file or patch the registration view (core/views/user.py registration() >> FormClass = RegistrationFormNoCaptcha). But you are right that it is not clear how to do it, I'll probably make this configurable and deactivated by default.

And as for being able to manage multiple people, the software is constructed so that every workout, log, etc, belongs to the user that created it. The closest there is for this is the gym management, where a trainer has an overview over other users.

**Comment by rolandgeider** [comment]
Your default admin user should already have access to it, in the right you should see an entry called "gyms". I think there is even a default gym created during installation, but I'm not sure. How this works is something that is not documented at the moment, but it's something that I plan to do in #114, but here's an overview:

Roles:
* general managers, who can add and delete gyms
* managers, who are responsible for a specific gym and can add other members, etc.
* trainers, who are responsible for the members

While the admin user should have all the permissions, I strongly suggest that you create at least a manager and a trainer and see how the software works with them (for this go into a gym and select "add member")

**Comment by fitbodylife** [comment]
There’s really no where i can put the captcha keys in .
at (core/views/user.py when i try to comment out the line, the app breaks.

any pointers would be appreciated. thanks so much

Khoi Nguyen
Managing Director
3400 W MacArthur Blvd. Suite C
Santa Ana, CA 92704
714-902-9584 ext 700
714-362-9068 fax
www.mobilechipmunk.com

        


On January 4, 2015 at 1:26:03 AM, Khoi Nguyen (khoi@mobilechipmunk.com) wrote:

Great.  how do i activate or use the gym management

Khoi Nguyen
Managing Director
3400 W MacArthur Blvd. Suite C
Santa Ana, CA 92704
714-902-9584 ext 700
714-362-9068 fax
www.mobilechipmunk.com

        


On January 4, 2015 at 1:24:29 AM, Roland Geider (notifications@github.com) wrote:

Hi! Do you mean in a local installation? You either need to enter reCaptcha keys in your settings.py file or patch the registration view at  registration() >> FormClass = RegistrationFormNoCaptcha). But you are right that it is not clear how to do it, I'll probably make this configurable and deactivated by default.

And as for being able to manage multiple people, the software is constructed so that every workout, log, etc, belongs to the user that created it. The closest there is for this is the gym management, where a trainer has an overview over other users.

**Comment by rolandgeider** [comment]
I see now that the sentence wasn't very clear, in users.py I meant to change the line

```
FormClass = RegistrationFormNoCaptcha if is_app else RegistrationForm
```

to simply

```
FormClass = RegistrationFormNoCaptcha
```

**Comment by rolandgeider** [comment]
@fitbodylife I'm guessing you got the application to run, so I'm closing the issue, feel free to open a new one if you encounter other problems
