### ISSUE TITLE
Enter weight along with the repetitions

### ISSUE THREAD

**Issue by rolandgeider** [rolandgeider/wger#119]
Allow the user to enter a (static) weight when adding sets. This is not as intelligent as #87 but is much simpler to implement (and understand)

**Comment by dfteam1** [comment]
I would love to see this feature implemented.
That way I could track the weight I use for each exercise and increase it as needed.
Thank you!

**Comment by rolandgeider** [comment]
This has been in my todo list for a while, I'll try to get it into 1.6

**Comment by rolandgeider** [comment]
TODO:

- [ ] DB-Upgrade
- [ ] canonical_representation for days and probably also reps_smart_text
- [ ] Workout views
- [ ] PDFs
- [ ] Timer
- [ ] REST-API (make field searchable, etc.)

**Comment by rolandgeider** [comment]
Started working on this in branch [issue119](https://github.com/rolandgeider/wger/tree/issue119). So far, it's coming along nicely :)

**Comment by rolandgeider** [comment]
Done
