### ISSUE TITLE
Allow copying workout of different user

### ISSUE THREAD

**Issue by rolandgeider** [rolandgeider/wger#127]
When accessing a workout of another user (and one is logged in) allow to copy the workout for own use

**Comment by max111** [comment]
How can I access the workout of another use (one who's not logged on)?

**Comment by rolandgeider** [comment]
The user first has to allow external access to his/her data, that's just a flag in the preferences. Then you can access the workout if you know the URL, in reality you would arrive there because it was shared in facebook or similar
