### ISSUE TITLE
Show last entries in body weight page

### ISSUE THREAD

**Issue by rolandgeider** [rolandgeider/wger#128]
The body weight page should show the last 5 (more?) entries. As a bonus it could show the change with respect to the previous entry, e.g.

Date | Weight | Change | Days
-------|------------|-------------|----------
30.01.2015   | 77,9     | -0,1 | 2
28.01.2015   | 78        | +2 | 8
20.01.2015   | 76        | 0 | 9
11.01.2015   | 76        | +0,3 |  12
30.12.2014   | 75,7     | +0,2 | 29
01.12.2014   | 75        | -/- | -/-

**Comment by rolandgeider** [comment]
Date | Weight | Change | Days
-------|------------|-------------|----------
30.01.2015   | 77,9     | -0,1 | 2
28.01.2015   | 78        | +2 | 8
20.01.2015   | 76        | 0 | 9
11.01.2015   | 76        | +0,3 |  12
30.12.2014   | 75,7     | +0,2 | 29
01.12.2014   | 75        | -/- | -/-

**Comment by max111** [comment]
Hi Roland, 

I'm quite new to open source contributions, and stumbled upon this project through openhatch which I think is quite interesting and an app I can imagine getting excited about & actually using it for myself. Is this project/issues items still open for fix? I'd like to attempt the patches but not quite sure since I don't see many people on this.

**Comment by rolandgeider** [comment]
Hi @max111 !

yes, this item is still open and honestly, I have been tempted to do it since I would like to have this feature for myself :) I have the next days free so I can help you setup an instance of wger and help you with whatever questions you might have

**Comment by max111** [comment]
HI Roland,

Okie Awesome! Thanks for the prompt response! I've been able to set up,  thanks to the great readme. And now I'm familiarizing myself with it. Could I shoot you a private message by email for questions I might have?

**Comment by rolandgeider** [comment]
Sure, just use the email I use in my commits

Am 3. Juni 2015 18:56:02 MESZ, schrieb max111 <notifications@github.com>:

**Comment by max111** [comment]
Sent !

**Comment by rolandgeider** [comment]
Issue was fixed with pull request #147
