### ISSUE TITLE
Calendar isn't showing the couloured (weight) logs

### ISSUE THREAD

**Issue by voszp** [rolandgeider/wger#131]
After creating a (weight) log the calendar is expected to highlight that certain date in green, orange or red.

**Comment by rolandgeider** [comment]
Hi @voszp, thanks for the report. How are you adding the logs? I just did some tests and it correctly marks the day in the calendar. By the way, are you using a local installation or the one at wger.de?

**Comment by rolandgeider** [comment]
Could reproduce this. The technical reason is that if there is a WorkoutSession entry without any WorkoutLog, nothing is shown in the calendar.

**Comment by voszp** [comment]
I'm using both the online version and a selfhosted dev-version running on an arm machine with Ubuntu Server. 
I also found another reason for missing WorkoutLog entries:
Creating a WorkoutLog and leaving the weights blank won't work as well. It's a bit weird entering weights after doing a bodyweight workout. 
This can be prevented by setting at least one weight field to zero. Maybe it's possible to set blank fields from bodyweight excercises automatically to zero?

**Comment by rolandgeider** [comment]
Nice to see that the app works with arm as well.

Yes, logging "zero weight" is a bit weird. On the other hand for some exercises it's possible to add additional weights (chains, etc.) so having a number here is OK. I personally use the timer view a lot and there the last entry (including "0") is used as a pre-selection.

**Comment by rolandgeider** [comment]
@voszp The bug with the calendar highlighting is fixed in master, in case you want to update your local installation
