### ISSUE TITLE
Request: Include stretching exercises

### ISSUE THREAD

**Issue by voszp** [rolandgeider/wger#134]
Add the possibility to add stretching exercises to workouts. Requires the opportunity to add and manage stretching exercises like exercises.

**Comment by rolandgeider** [comment]
This and cardio exercises (basically time based exercises) are something I definitely want to add to the application. I still need to think on how to implement this without breaking everything, since many parts assume that there are repetitions.

**Comment by rolandgeider** [comment]
Cautiously moving this to 1.7

**Comment by rolandgeider** [comment]
Well, it took a while, but time based exercises are now supported! :D (basically, when adding exercises to a set, it is possible to select a unit such as "repetitions" or "minutes", "kilometres"). Closing here.
