### ISSUE TITLE
Add dummy weight generation

### ISSUE THREAD

**Issue by rolandgeider** [rolandgeider/wger#145]
The dummy data generation script needs to be able to generate weight entries

**Comment by max111** [comment]
What's the purpose for the dummy weight generations?

**Comment by rolandgeider** [comment]
The dummy data generator is meant as a help to populate the database with data. E.g. the gym management has some usability issues that are only visible with many users and I wanted to be able to generate data for all important modules

**Comment by rlaszlo** [comment]
Hi @rolandgeider ,

I think I can help with this. Do you have anything in mind for the data generation?

I have some questions:
* It should be the same like the workout generator? Generate for given user or all of them?
* The weight data can be randomized? Maybe between minimum and maximum weight?
* The entry creation date should be randomized like in the workout generator?

**Comment by rolandgeider** [comment]
Hey!

Awesome! Yes, it should work similarly to the workout generator. It should also randomise the data so that it looks more or less realistic, perhaps you can take a look at demo.py, there is something similar for demo users. The main point of the generator is to find usability problems with the app, so in the end it doesn't really matter too much how the numbers look like :)

Am 8. Juni 2015 19:22:46 MESZ, schrieb "Ratskó László" <notifications@github.com>:

**Comment by rolandgeider** [comment]
Closed with #152
