### ISSUE TITLE
BMI And Calorie Calculator Not Working

### ISSUE THREAD

**Issue by dfteam1** [rolandgeider/wger#146]
Using this software in Linux Mint 13.
When I enter my data into either the BMI calculator or the calorie estimator nothing happens.
I have entered my height in cm and my weight in kgs.
The BMI calculator says my BMI = 0.
I'd be happy with 10.

**Comment by rolandgeider** [comment]
I'll take a look

**Comment by rlaszlo** [comment]
Hi!

I checked out the BMI calculator and I think that the problem could be with the BmiForm validation. It only accepts decimal for the weight field and and gets the Integer field from the Model.

@dfteam1 did you use a non integer value in the height field?

@rolandgeider Do you think that we can show the form validation errors? I can do it if that is okay.

**Comment by rolandgeider** [comment]
Yes, the decimal input seems to trigger this. Showing errors is always a good idea, but this form is a bit AJAXy and I would prefer something more general for this. I would suggest that we just fix this specific bug. @rlaszlo do you want to give it a try? If not, I can do it

**Comment by rlaszlo** [comment]
Yes, I'm working on it now. Should I migrate the UserProfile.height field to Decimal or just add a new Decimal field for the BmiForm?

**Comment by rolandgeider** [comment]
No, don't migrate the field, better solve it in the form

**Comment by rolandgeider** [comment]
oh, BTW, if you solve this and make a pull request, send it to my "release" branch

**Comment by rolandgeider** [comment]
At least the problem with the decimals is fixed with the pull request. Closing here
