### ISSUE TITLE
Terms of service & privacy policy

### ISSUE THREAD

**Issue by baldurmen** [rolandgeider/wger#155]
Hi!

Do you think you could add a privacy policy on the public instance of WGER? I'd like to use it since building a private instance for myself is a bit overkill, but I'd also like to know you do with our data.

Personally, I think Riseup's privacy policy is great and protects users. Maybe you could get some inspiration from it?

https://help.riseup.net/en/about-us/policy
https://github.com/riseupnet/riseup_help/tree/master/pages/about-us/policy

**Comment by rolandgeider** [comment]
Hi!

I've been thinking about adding one for some time, but didn't know were to start or how to word them. In any case, those you linked to seem like a nice starting point!

**Comment by rolandgeider** [comment]
@baldurmen I just took a look at the TOS of riseup and used what seemed sensible for this service. I have also just updated the [website](https://wger.de/en/software/terms-of-service). If you feel there is something missing, just re-open this issue!
