### ISSUE TITLE
Request: Need An Option To Delete Workout From Calander  

### ISSUE THREAD

**Issue by heroics** [rolandgeider/wger#156]
I input a workout on the wrong day and there does not seem to be an option to delete the workout.

**Comment by rolandgeider** [comment]
@heroics I have just updated the site, there is now a button in the calendar page to delete the workout session, either with or without the corresponding weight logs :)

**Comment by heroics** [comment]
Right on! I'm still learning how to program, but as soon become proficient enough I will help with this project.

**Comment by rolandgeider** [comment]
Python is a really cool language, you'll like it! And once you are ready to get dirty with wger, feel free to ask me anything if it's not clear how anything works or such :)
