### ISSUE TITLE
Default author for exercises should be hostname

### ISSUE THREAD

**Issue by rolandgeider** [rolandgeider/wger#159]
At the moment, the author used for exercises when added by an administrator is the hard coded string 'wger.de'. This should be changed to the current hostname so that local installations get sensible data.

**Comment by jamessimas** [comment]
Looking into this.

**Comment by jamessimas** [comment]
I've just learned what interactive rebasing is, so my future pull requests should be cleaner. Huzzah!

James

**Comment by rolandgeider** [comment]
I know that some projects practically demand to rebase everything for push requests, but I am more relaxed, if you needed 5 commits, then I get those 5 commits, they don't hurt. But obviously, if you want to tidy up the commits, feel free! :smile: (BTW, you can also rebase commits in a pull request after you have opened it, even multiple times)

**Comment by jamessimas** [comment]
Good to know. Thanks.!

**Comment by rolandgeider** [comment]
Implemented with pull request #166
