### ISSUE TITLE
On the fly workout

### ISSUE THREAD

**Issue by stenox** [rolandgeider/wger#174]
It would be very usefull to have possibility of "On the fly workout".
That means that I could go to the gym and choose the exercises on the fly, not only within selected workout.

**Comment by rolandgeider** [comment]
Hi @stenox! That's a feature that's been on my TODO list for a while, there's a issue for that, #64. I can't say when it will be ready, but it has priority within the 1.7 milestone.

I'm closing this issue, if you are interested in the progress, subscribe to the other issue

**Comment by stenox** [comment]
I see. Sorry, I didn't find that by search.
Thanks!

**Comment by rolandgeider** [comment]
No problem!

If you have other ideas, feel free to open as many issues as you like
