### ISSUE TITLE
Disabled Administration link

### ISSUE THREAD

**Issue by svengineer** [rolandgeider/wger#183]
I installed wger manually from the github repo. After login in as "admin", I tried to go to Administrator -> Administration. But "Administration" has no Link. It's just grey text.

![wger_administration_menu](https://cloud.githubusercontent.com/assets/5602831/9562786/c8ceac06-4e76-11e5-952c-51486c777dde.png)

**Comment by rolandgeider** [comment]
Ah, I see now what you meant the other day, that is actually just a heading. I can see that it can look like it was disabled, but that's bootstrap's default theme. It will probably get more clear once there are other sections.

I'm closing the issue, but if you have a suggestion on how to make it more clear, let's hear them :)
