### ISSUE TITLE
"Bad request" after changing settings: "DEBUG = False"

### ISSUE THREAD

**Issue by svengineer** [rolandgeider/wger#185]
After changing the settings from "DEBUG = True" to "DEBUG = False" I'm always getting a "Bad request". It's not important for me but an unexpected behavior.

**Comment by rolandgeider** [comment]
The error in the command line is: ``Invalid HTTP_HOST header: 'localhost:8000'. You may need to add u'localhost' to ALLOWED_HOSTS.``

I think a note in the documentation and a comment in the generated settings should be enough for this.

**Comment by rolandgeider** [comment]
Should be done after #184

**Comment by rolandgeider** [comment]
Allowed hosts is now set to ``*`` when creating new settings, should fix this problem.
