### ISSUE TITLE
Android Mobile Firefox weight entry fails

### ISSUE THREAD

**Issue by PolarFox** [rolandgeider/wger#192]
Adding weight entry fails because date selector resets to empty for some reason. Locale is finnish.

**Comment by rolandgeider** [comment]
Thanks for the report, will investigate once my computer is repaired.

**Comment by rolandgeider** [comment]
@PolarFox I'm trying to reproduce this, what happens exactly, does the date simply disappear when you try to save the form?

**Comment by PolarFox** [comment]
It disappears, when date field is blurred.

----- Alkuperäinen viesti -----
Lähettäjä: "Roland Geider" <notifications@github.com>
Lähetetty: ‎26.‎9.‎2015 20:40
Vastaanottaja: "rolandgeider/wger" <wger@noreply.github.com>
Kopio: "PolarFox" <polarfox@polarfox.net>
Aihe: Re: [wger] Android Mobile Firefox weight entry fails (#192)

@PolarFox I'm trying to reproduce this, what happens exactly, does the date simply disappear when you try to save the form?

**Comment by rolandgeider** [comment]
Also, bootstrap's and chrome's datepickers both open at the same time. I'm tending towards just removing our own datepicker and relying on the browser providing one, plus providing sensible default (I suppose django can take care of the different date formats if we just give it a python date object)

**Comment by rolandgeider** [comment]
I've removed the datepicker, this seems to take care of the problem. Will update wger.de (and with it, the mobile app) in the next days.
