### ISSUE TITLE
Text overflowing in dashboard

### ISSUE THREAD

**Issue by rolandgeider** [rolandgeider/wger#194]
Depending on the locale and window size, the text in the dashboard buttons shown if the user has no workouts can overflow. This can be solved with a bit of CSS magic.

![bildschirmfoto am 2015-09-23 um 16 26 50](https://cloud.githubusercontent.com/assets/2280729/10047849/57af6558-6210-11e5-9173-de769dbe74fd.png)

**Comment by romansp** [comment]
Hi, @rolandgeider. Found your project at http://up-for-grabs.net. 

Took a glance at source code and site, and found some more minor css/html issues. I want to grab this issue and can create another PR with of all other minor tweaks.

Now, regarding this issue. It's obviously site-wide ([take a look](https://cloud.githubusercontent.com/assets/3474842/10112659/9dff0744-63e5-11e5-9330-e9588cd2c6c0.png)) and affects all buttons with long texts. Possible css solutions can be:
**Clipping**:
 ![image](https://cloud.githubusercontent.com/assets/3474842/10112427/bb14a160-63e3-11e5-9ee0-71dff270b7ae.png)

**Ellipsis**:
![image](https://cloud.githubusercontent.com/assets/3474842/10112441/e2908fe2-63e3-11e5-92e7-9553352f12fe.png)

**Allow multiline text inside button**: 
![image](https://cloud.githubusercontent.com/assets/3474842/10112451/f372eb98-63e3-11e5-92a1-397d9790b1d9.png)

Which one will fit better?

**Comment by rolandgeider** [comment]
hi @romansp! I think the ellipsis is the better solution, allowing multiline text might break the layout in some parts. Pull request for any issues you might find are of course always welcome :)
