### ISSUE TITLE
Nutrition plan: pick correct body weight entry

### ISSUE THREAD

**Issue by rolandgeider** [rolandgeider/wger#210]
In the ``get_nutritional_values`` method of ``NutritionPlan`` the per-kg-calculation uses the user's last weight entry. While this is correct when adding meals to the plan, it can be wrong when opening the plan later (the user's weight changed). This should be changed so that the weight entry *closest to the plan's date* should be used.

**Comment by avinsrid** [comment]
I can take a look at this

~Avinash

**Comment by rolandgeider** [comment]
:+1:

**Comment by rolandgeider** [comment]
Hey @avinsrid, how is it going?
