### ISSUE TITLE
Specify different repetition options while adding exercises to a workout

### ISSUE THREAD

**Issue by umuzidan** [rolandgeider/wger#216]
As a User, I want the ability to specify different repetition options while adding exercises to a workout
Repetition Options:
1) Reps
2) Until Failure
3) Seconds
4) Minutes
5) Feet
6) Miles
7) Kilometers

Background: While creating various exercise routines, users may choose to run, bike, walk, etc. These activities can persist for a time duration, distance, or until failure.

**Comment by rolandgeider** [comment]
Yes, this is something I've had in my roadmap for a long time. The original issue is #134, which was originally only about stretching exercises.

**Comment by rolandgeider** [comment]
Started working on it in my [rep-options](https://github.com/rolandgeider/wger/tree/rep-options) branch

**Comment by rolandgeider** [comment]
Took a big longer than expected, but this is now merged in master
