### ISSUE TITLE
Deleting all gyms and then creating a new gym throws error.

### ISSUE THREAD

**Issue by purplebird** [rolandgeider/wger#236]
To reproduce:

1) Delete all the gyms
2) Create a new gym
3) Try to view the gym members

---

NoReverseMatch at /en/gym/6/members

Reverse for 'edit' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['en/gym/admin-config/(?P<pk>\\d+)/edit$']

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/en/gym/6/members
Django Version: 	1.8.6
Exception Type: 	NoReverseMatch
Exception Value: 	

Reverse for 'edit' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['en/gym/admin-config/(?P<pk>\\d+)/edit$']

**Comment by rolandgeider** [comment]
Good catch!

I have added a check in the template, since this constellation could also potentially happen through other ways.
