### ISSUE TITLE
Dev Install Fails To Recognize Bower Installation

### ISSUE THREAD

**Issue by ab5y** [rolandgeider/wger#254]
![image](https://cloud.githubusercontent.com/assets/4251453/12302635/22b32076-ba4c-11e5-8c88-9621dbe1d823.png)

I keep getting the BowerNotInstalled exception when trying to run the invoke command.

**Comment by rolandgeider** [comment]
Hi!

Did you install bower globally? At the moment the application assumes this is installed locally within the source folder. It might be enough to change the ``BOWER_PATH`` variable in ``wger/settings_global.py`` but that's something I haven't tested.
