### ISSUE TITLE
Support for custom ingredients

### ISSUE THREAD

**Issue by ywecur** [rolandgeider/wger#256]
Since you cannot add a custom food item to your meal plan if it isn't already in the database I believe this feature to be essential.

Additionaly, being able to add ingredients while creating a meal plan should be possible.

**Comment by rolandgeider** [comment]
You can submit ingredients that can be added to the database. Or do you mean something like "composed ingredients" which are e.g. a combination of other ingredients?

**Comment by ywecur** [comment]
Sorry if I'm just ignorant, but I can't find where to add ingredients. By add I mean enter a name, calories/gram, micronutients etc.

**Comment by rolandgeider** [comment]
If you go to the ingredients list you should see an option to add one, similar to adding exercises newly submitted ingredients aren't added right away

**Comment by rolandgeider** [comment]
This is now fixed and wger.de updated

**Comment by ywecur** [comment]
Great job, and thank you for this fantastic piece of software!

**Comment by rolandgeider** [comment]
Thanks:)
