### ISSUE TITLE
Language change is not working 

### ISSUE THREAD

**Issue by EmilAlipiev** [rolandgeider/wger#257]
When I login, it recognizes automatically my language as German while my location is Germany but when I change with English and want to add new workout with exercises, In the auto complete box, i cant get any result in English. All website is in English but When I type "Bench", I don't get anything while if I type "Bank", I get German results.

**Comment by rolandgeider** [comment]
You are right, something's not working right here

**Comment by rolandgeider** [comment]
Just fixed this, I'll try to update the site this weekend
