### ISSUE TITLE
Can't invoke bootstrap_wger ECONFLICT 

### ISSUE THREAD

**Issue by s1mpleman** [rolandgeider/wger#259]
Hi there, I keep getting an error where jquery is conflicting in bower. I've tried googling it to no joy, has anyone any ideas at all? 
Running:
>invoke bootstrap_wger --settings-path /home/wger/src/settings.py --no-start-server

Gives me: 

>bower jquery#*                  cached git://github.com/jquery/jquery-dist.git#2.2.0
>bower jquery#*                validate 2.2.0 against git://github.com/jquery/jquery-dist.git#*
>bower d3#*                      cached git://github.com/mbostock/d3.git#3.5.13
>bower d3#*                    validate 3.5.13 against git://github.com/mbostock/d3.git#*
>bower shariff#*                 cached git://github.com/heiseonline/shariff.git#1.22.0
>bower shariff#*               validate 1.22.0 against git://github.com/heiseonline/shariff.git#*
>bower bootstrap#*               cached git://github.com/twbs/bootstrap.git#3.3.6
>bower bootstrap#*             validate 3.3.6 against git://github.com/twbs/bootstrap.git#*
>bower tinymce-dist#*            cached git://github.com/tinymce/tinymce-dist.git#4.3.3
>bower tinymce-dist#*          validate 4.3.3 against git://github.com/tinymce/tinymce-dist.git#*
>bower DataTables#*              cached git://github.com/DataTables/DataTables.git#1.10.10
>bower DataTables#*            validate 1.10.10 against git://github.com/DataTables/DataTables.git#*
>bower components-font-awesome#* cached git://github.com/components/font-awesome.git#4.5.0
>bower components-font-awesome#*         validate 4.5.0 against git://github.com/components/font-awesome.git#*
>bower tinymce#*                           cached git://github.com/tinymce/tinymce-dist.git#4.3.3
>bower tinymce#*                         validate 4.3.3 against git://github.com/tinymce/tinymce-dist.git#*
>bower jquery#>= 2.1.0                     cached git://github.com/jquery/jquery-dist.git#2.2.0
>bower jquery#>= 2.1.0                   validate 2.2.0 against git://github.com/jquery/jquery-dist.git#>=2.1.0
>bower jquery#>=1.2                        cached git://github.com/jquery/jquery-dist.git#2.2.0
>bower jquery#>=1.2                      validate 2.2.0 against git://github.com/jquery/jquery-dist.git#>=1.2
>bower jquery#>=1.6                        cached git://github.com/jquery/jquery-dist.git#2.2.0
>bower jquery#>=1.6                      validate 2.2.0 against git://github.com/jquery/jquery-dist.git#>=1.6
>bower jquery#~2.1.1                       cached git://github.com/jquery/jquery-dist.git#2.1.4
>bower jquery#~2.1.1                     validate 2.1.4 against git://github.com/jquery/jquery-dist.git#~2.1.1
>bower                                  ECONFLICT Unable to find suitable version for jquery

**Comment by geosony** [comment]
Yeah, same issue happened for me. Please change the "interactive" to true in ~/wger/.bowerrc.
It will prompt for the options if any dependency is not available. I've answered option 1 for the question requested jquery version not found.

**Comment by s1mpleman** [comment]
OMG! that worked perfectly thank you so much. 

Option 1 worked as suggested as well. 

Although I found .bowerrc in ~/wger/src

**Comment by rolandgeider** [comment]
Thanks for reporting this.

I need to find a solution that does not involve changing the interactive flag, perhaps by changing the jquery requirement. The reason for this is that I need the installation to happen automatically, e.g. when used in docker where no user input is possible. I don't know when I'll be able to look into this, as my SSD recently went pinning to the fjords.

**Comment by s1mpleman** [comment]
No trouble at all, was happy to get it solved. Maybe a little note in the production documentation would help for now? 

Sorry to hear about your SSD as well, had to urban dictionary pinning to the fjords though, and now feel embarrassed because it was Monty Python!

**Comment by rolandgeider** [comment]
it's from the dead parrot sketch :smile:

**Comment by s1mpleman** [comment]
Great sketch!

**Comment by rolandgeider** [comment]
I did changed the default value for the interactive flag, at least this makes the installation work for most. I still want this to happen without any interaction, probably just need to specify a specific version of the libraries.

**Comment by rolandgeider** [comment]
The required version of jquery is now explicitly set in the configuration file, that should take care of  the ECONFLICT thing. I have done some quick tests and everything seems to be working fine, so I'm being bold and have also reverted the interactive flag back to false. If you guys still have troubles, just comment here :)
