### ISSUE TITLE
iFrames Blocked

### ISSUE THREAD

**Issue by s1mpleman** [rolandgeider/wger#262]
Hello, awesome application! Been using it to track my physio and it's working great. 

I however at home, put all my applications under an iframe so that I can quickly switch between each one. 

I'm not expecting a recode or anything, could someone point out where the bit I would need to change to allow iFrames would be? my python is very limited at the moment.

**Comment by rolandgeider** [comment]
Glad you like it :)

This is active by default to prevent [clickjacking](https://docs.djangoproject.com/en/1.9/ref/clickjacking/), but obviously there are circumstances where you'd want to allow that. Just edit ``wger/settings_global.py`` and remove in ``MIDDLEWARE_CLASSES`` the line one with ``XFrameOptionsMiddleware``.

**Comment by s1mpleman** [comment]
Thank you very much! 
Thanks for the documentation as well, I'll have a read. I'd heard of it, but I'm guessing my local install wouldn't come under such threats? It's not accessible via the internet anyway, I just prefer a web implementation as I can manage that on Android without the need for a 3rd party. This app fits that bill perfectly.

**Comment by s1mpleman** [comment]
I changed that file on my install, I removed the line 'django.middleware.clickjacking.XFrameOptionsMiddleware',

It's still showing a white page when I access it through an iframe though. 

Would I be better setting this? 

from django.http import HttpResponse
from django.views.decorators.clickjacking import xframe_options_exempt

'@xframe_options_exempt
def ok_to_load_in_a_frame(request):
    return HttpResponse("This page is safe to load in a frame on any site.")'

**Comment by rolandgeider** [comment]
Thanks for the kind words! This is really just a hobby of mine (though it has gotten much bigger and popular than I ever expected). If you want to "give something back", you are welcome to add or correct exercises on wger.de (they flow back to this repo when I do a release which I plan to do in February).

And about the clickjacking, realistically, even if you had it on the internet the risk would be minimal, so don't worry about it.

**Comment by s1mpleman** [comment]
I've added a few already, but it's only on my local. Is there any way to sync the two? or would manually be the only option? I'm happy to do either, I'll just add a list of what I add and then update them every week or so when I get time. Just mainly things like Hip Raises and Reverse Crunches at the min due to my physio. 

Oh and you've certainly done more than the Romans have done for us! ;)

**Comment by rolandgeider** [comment]
No, at the moment there is no way to sync them. In theory you could cook up some script that hits the REST API (doesn't need to be python), but till then it would need to be manually.

**Comment by s1mpleman** [comment]
No trouble at all, I'll go make an account because at the min it's probably easier manual than coming up with a script.

**Comment by rolandgeider** [comment]
Cool. Tell me your username so I can give you the necessary permissions, then you can add or edit them directly.
