### ISSUE TITLE
Fix typos and strings

### ISSUE THREAD

**Issue by rolandgeider** [rolandgeider/wger#264]
* [x] Trainer, can see the users for a gym, It should either be "Trainer: can see the users for a gym" or "a trainer can see the users for a gym". Same applies to entries bellow this one. This needs a DB upgrade since this is one of the custom permissions
* [x] "Pending images" to "Images pending review" (or ingredients, exercises, etc.)
* [x] "Reminder inactive members" sounds strange, this should either be "Reminder: inactive members" or "Reminder of inactive members"

**Comment by ywecur** [comment]
Should I add the items here instead of as comments on Transifex?

**Comment by rolandgeider** [comment]
Keep adding them in transifex, this issue is for things that can't be just fixed right away (e.g.because they are in the database, should be reviewed in context, etc.)

**Comment by rolandgeider** [comment]
BTW, I'll install your translation to the preview server, so you can check them in context, I'll let you know once I'm done.

**Comment by ywecur** [comment]
Alright, thanks!
