### ISSUE TITLE
Extended PDF options for schedules

### ISSUE THREAD

**Issue by rolandgeider** [rolandgeider/wger#272]
The PDF generator for schedules should be extended so that it has the same options as the regular workout (images, comments, etc.). This should be fairly easy, since most of the logic and code from the workout view, urls, etc. will work as well

**Comment by alelevinas** [comment]
i'm on it :)

**Comment by rolandgeider** [comment]
Great! :)

**Comment by rolandgeider** [comment]
PR merged, closing here
