### ISSUE TITLE
Out of bounds weight error for the morbidly obese

### ISSUE THREAD

**Issue by azend** [rolandgeider/wger#275]
Users over 300 lbs cannot enter their weight into the tracker because it is out of bounds for the model. Given the typical stereotype of an american diet, the max bounds should be increased to something more realistic. Say 600 lbs?

**Comment by rolandgeider** [comment]
You are right, at first the application only supported metric units so 300 kg was enough :)

**Comment by rolandgeider** [comment]
Issue closed, PR was merged
