### ISSUE TITLE
Piwik?

### ISSUE THREAD

**Issue by Lvl4Sword** [rolandgeider/wger#278]
Using uBlock Origin I noticed that there was a connection to uberspace.de and so I opened the Network option in the developer settings in Iceweasel. I saw the only reason wger connects to this domain is to access Piwik at https://rge.vela.uberspace.de/piwik.js and a long URL starting with https://rge.vela.uberspace.de/piwik.php?action_name= that sends the resolution of my screen, and sets a cookie, among a few other things. I wasn't told anywhere about this

( when i say "this", i mean the resolution/cookie/etc. The only mention of Piwik is the following: "Aonymized usage: we use a local instance of the analytics software piwik. The IP addresses are saved in a pseudo-anonymized form (last octet removed) and are later deleted when the data has been processed." from https://wger.de/en/software/terms-of-service ),

It wasn't conveyed that this would occur. Is this really necessary?

EDIT: The first place I can tell this occurs is on the REGISTRATION PAGE (?!). The data sent looks like this:
https://rge.vela.uberspace.de/piwik.php?action_name=Register&idsite=&rec=&r=&h=&m=&s=&url=http%3A%2F%2Fwger.de%2Fen%2Fuser%2Fregistration&_id=&_idts=&_idvc=&_idn=&_refts=&_viewts=&send_image=&cookie=&res=&gt_ms=
Obviously I removed the information. The questions still stand though, why do you need/care about all of this? Why is it not in your terms of service that this would occur?

**Comment by Lvl4Sword** [comment]
The first place I can tell this occurs is on the REGISTRATION PAGE (?!). The data sent looks like this:
https://rge.vela.uberspace.de/piwik.php?action_name=Register&idsite=&rec=&r=&h=&m=&s=&url=http%3A%2F%2Fwger.de%2Fen%2Fuser%2Fregistration&_id=&_idts=&_idvc=&_idn=&_refts=&_viewts=&send_image=&cookie=&res=&gt_ms=
Obviously I removed the information. The questions still stand though, why do you need/care about all of this? Why is it not in your terms of service that this would occur?

**Comment by rolandgeider** [comment]
Hi there!

I guess it could be written more clearly what is collected. Many of these infos are things that I don't need, but as far as I can tell it's not possible to tell piwik to not collect all it can (for what it's worth, the uberspace server is also mine so nothing is being sent anywhere). Information such as screen resolution can be useful to have e.g. to see in which sizes the application is used etc. Also, piwik is configured to respect the Do Not Track header, so if it's being sent, nothing is logged at all.

**Comment by Lvl4Sword** [comment]
In regards to the Do Not Track header, most websites don't respect it. It also increases your fingerprint ( https://panopticlick.eff.org/ ).

Screen resolutions are not important, and sites like github have a mobile/desktop version, and the height/width works perfectly for the user's resolution. it would be trivial to implement this into your program without trying to uniquely identify users via cookies/resolutions/ip addresses/etc.

the fact that the uberspace server is yours doesn't matter, and we can't tell if you're actually saving this information. so, you can understand why it's questionable you'd need piwik setup at all.

which brings me onto your statement of "Many of these infos are things that I don't need, but as far as I can tell it's not possible to tell piwik to not collect all it can". if you don't need them, and have no clue how to limit this collection, why would you use piwik at all? piwik is open source as touted on their website. i'm surprised you wouldn't be able to edit an open source program to work the way you'd need.

but, i still stand by what i said before. not sure why you would need piwik at all :-)

**Comment by rolandgeider** [comment]
I mean, perhaps it increases the fingerprint but that shouldn’t be a reason not to use it (because the same will happen by using linux or another non mainstream operating system). And patching piwik so that it doesn't save the data that I don't use is simply not practical, specially since this would have to happen for every release. In the end, I use piwik for the *other data* that I do find interesting, which is presented in a nice and clean way with different charts etc. And it's not like the tracking snippet is in the upstream code, this is just for the instance that I am running (adding it there would be really unnecessary and an invasion of privacy).

**Comment by Lvl4Sword** [comment]
You just admitted this was an invasion of privacy, so why would you be running it on your instance?

**Comment by rolandgeider** [comment]
Because there is a difference between tracking the use of every instance of the software and only the one I provide

**Comment by Lvl4Sword** [comment]
It still stands that you should let others know on your own installation. I personally would not have created an account ( and then deleted it ) if this was in the fine print. So the practice of not explaining this in your terms of service/privacy policy is very deceptive.

**Comment by rolandgeider** [comment]
I have updated the TOS explaining a bit more in detail what piwik collects, also mentioning the possibility to use the Do Not Track header.

**Comment by Lvl4Sword** [comment]
Not quite sure why this was closed, considering this is still an issue.

> Aonymized usage: we use a local instance of the analytics software piwik. **The IP addresses are saved in a pseudo-anonymized form (last octet removed) and are later deleted when the data has been processed.** Piwik tracks browser settings such as browser type and version, resolution, language used among others, as well as application infos such as the time needed for the pages to be rendered. The piwik installation is configured to respect the Do Not Track header, if you have your browser configured to send it, piwik will not track you at all.
> Information we choose to not retain
> 
> IP addresses: **The server generates access and error logs that are used to identify problems, but your IP address is not logged at all. **

so, is the ip address _'saved'_, or _'logged'_, and what's the difference?

**Comment by rolandgeider** [comment]
Saved and logged mean here the same, I just didn't want to always use the same word. The "saved" refers to piwik which has its own database and "logged" refers to the webserver logs (because the application is run behind a reverse proxy, there are no IP address written to the logfile). As for the issue original issue, after making it clearer in the TOS what is collected, I'm not sure what else I can do besides removing piwik completely, which isn't really an option.
