### ISSUE TITLE
Introduce Myself - Jefferson (foguinho.peruca)

### ISSUE THREAD

**Issue by foguinhoperuca** [rolandgeider/wger#90]
Hello!

My name is Jefferson, I found wger in mozilla marketplace and installed it in my phone (Alcatel Onetouch - FirefoxOS 1.1).
I think this app is very promising and I would like to have some features like:

* Management of execution my nutrition plan - predicted versus realized
* Management to my medical appointments (cardiologist, endocrinologist, etc)
* Log of my sleep
* Port app (some features - like add weight entry, exercises entries, etc) to native FirefoxOS app (to use only when wifi is available)
* Translate app to PT_BR
* Control my own data (backup, privacy, etc)

So, what is the plans for app? Are you working in app yet? You have some advice to give (where start, etc)?

Thanks,
Jeff

**Comment by rolandgeider** [comment]
@foguinhoperuca I'm closing this issue, I have noted the points you mentioned in the beginning so they will not get lost. If you want to start hacking on it again or want me to help you with something, just ping me
